name: Generate Keystore

on:
  workflow_dispatch:
    inputs:
      password:
        description: 'Password (min 6 karakter)'
        required: true

jobs:
  gen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Buat keystore
        run: |
          keytool -genkeypair -v -keystore release.keystore \
            -alias gurubersbagi -keyalg RSA -keysize 2048 -validity 10000 \
            -storepass "${{ inputs.password }}" -keypass "${{ inputs.password }}" \
            -dname "CN=GuruBerbagi,C=ID"
          base64 -w 0 release.keystore > keystore.txt
      - uses: actions/upload-artifact@v4
        with:
          name: keystore
          path: keystore.txt
